---
- name: Run OpenShift Applier
  hosts: local
  gather_facts: no
  vars:
    ci_cd:
      namespace: labs-ci-cdryan
    dev:
      namespace: labs-devryan
    test:
      namespace: labs-testryan
  roles:
    - openshift-applier/roles/openshift-applier
